name: 'Lokalise API PUSH'
description: 'Triggers build on Lokalise that creates a PR'
author: 'Andreassim'

# Define your inputs here.
inputs:
  API_KEY:  # Lokalise API key
    description: 'API KEY'
    required: true
  PROJECT_KEY: #Lokalise Projekt key 
    description: "Project key"
    required: true

# Define your outputs here.
outputs:
  result:
    description: 'succesful or not'

runs:
  using: node20
  main: dist/index.js
